
# Site settings
title: YoshuaPortfolio
email: allidjinoumichee@outlook.fr
description: >- # this means to ignore newlines until "baseurl:"
  My personal portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yoshuaportfolio.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: allidjinou
github_username:  yoshua70

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-admin
